name: Python CI # The name of your workflow, displayed on GitHub

on: # Specifies the events that trigger this workflow
  push:
    branches: [ main ] # Run on pushes to the main branch
  pull_request:
    branches: [ main ] # Run on pull requests targeting the main branch

jobs: # Defines the jobs to run as part of the workflow
  build-and-test: # Name of the job
    runs-on: ubuntu-latest # Specifies the type of machine to run the job on (latest Ubuntu)

    strategy: # Defines a build matrix for your jobs (optional, but good practice)
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Test against multiple Python versions

    steps: # A sequence of tasks to be executed
      - name: Checkout code # Step 1: Check out your repository's code
        uses: actions/checkout@v4 # Uses a pre-built action from GitHub Marketplace

      - name: Set up Python ${{ matrix.python-version }} # Step 2: Set up the specified Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies # Step 3: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest # Step 4: Run your tests
        env: # Environment variables for this step
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_DUMMY }} # Use a dummy key for CI tests
        run: |
          pytest -v